### ISSUE TITLE
Ellipses point in the wrong direction

### ISSUE THREAD

**Issue by quantitative-ecologist** [caijun/ggcorrplot2#3]
Hi,
thank you very much for your nice package. I wanted to know if it is possible to change the orientation of the ellipses. I see that negative correlations are associated with the lower part of the color gradient, but the ellipses point upright (and downleft if the correlation is positive). I feel it could be misleading in thinking that the correlation is positive when negative, and vice-versa. Would it be possible to arrange that?

Thank you very much.

Maxime

**Comment by LDSamson** [comment]
Thanks for the package indeed, I really like it!

Regarding this bug: I've looked into the source code; the individual ellipses are calculated correctly, but when calling ggplot the y coordinates are reversed to maintain the order of variables as they are given in the input matrix; I think it is a bug indeed.

Easiest hack is of course just to reverse all rho values before calling the function. 

```r
reversed.matrix <- corr.matrix*-1
```

Another somewhat dirty trick is to reverse the ellipse coordinates in the source code :
```r
    x <- cos(theta - d / 2) / 2 #  instead of "+d/2"
    y <- cos(theta + d / 2) / 2 # instead of "-d/2"
```
A better fix might be to not reverse the y coordinates for the y axis when calling ggplot in the main function (use scale_y_continuous() instead of scale_y_reverse()), but I think that needs some careful rewriting of the code to get the labels correct again.

**Comment by caijun** [comment]
Thanks for raising this issue. I will fix it as soon as possible.

**Comment by mathesong** [comment]
Hey @caijun : I love the package, and I've been looking for something like this for ages!  Great work!

I ran into this same issue, so I made a little quick fix for the ellipse function, and I've created a pull request here: https://github.com/caijun/ggcorrplot2/pull/5

**Comment by caijun** [comment]
@mathesong thanks for your fix. I will close this issue via your PR https://github.com/caijun/ggcorrplot2/pull/5
